---
- name: Install MariaDB on centos/rethat
  package: pkg={{ item }} state=installed
  with_items:
  - mariadb-server
  - mariadb 
  - MySQL-python

- name: make sure service is activated at boot time
  service: name=mariadb state=restarted enabled=yes

- name: Change root password
  mysql_user: 
    name: root
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - localhost

- name: Create new DB
  mysql_db: name=MyDB state=present login_user=root login_password="{{ mariadb_root_password }}"

